### ISSUE TITLE
You probably need to update `s:URLEncode`

### ISSUE THREAD

**Issue by arp242** [statox/GOD.vim#2]
Encoding every non-letter character isn't quite right; some characters should *not* be encoded otherwise some browsers will break.

This is what I currently use, feel free to copy: https://github.com/Carpetsmoker/helplink.vim/blob/master/plugin/helplink.vim#L109

**Comment by statox** [comment]
Thank you for that!

I changed the regex to the one you use in your plugin in commit  8663aa5ba2ae. From the first tests I made, it works nicely.
